language: python

python:
    - "2.7"

before_install:
    - sudo pip install virtualenv
    - virtualenv $TRAVIS_BUILD_DIR/arteria-dsmc/

install:
    - source $TRAVIS_BUILD_DIR/arteria-dsmc/bin/activate
    - pip install -e . -r ./requirements/dev

script:
    - nosetests tests/

notifications:
    email: false
